### ISSUE TITLE
!help command

### ISSUE THREAD

**Issue by svimanet** [svimanet/chatbot#62]
A command to list available commands could be useful, and should not require much work. Good first issue!

**Comment by ChaseBosman** [comment]
With the dictionary of commands being local to the command method, would the preferred practice be to make the dictionary an instance variable instead of local? One would then be able to then be able to access the dictionary's keys from outside of the class in a help method. Thanks for the advice, it's my first open source contribution and I'm a bit confused on how to go about the process.

**Comment by ChaseBosman** [comment]
[https://github.com/svimanet/chatbot/pull/64](url)
Hopefully this is what you're looking for. Let me know. Thanks!

**Comment by ChaseBosman** [comment]
#64 
Related pull found above. Hopefully this is what you're looking for. Please let me know, thanks!

**Comment by svimanet** [comment]
Sorry for the delay, didn't expect contributions already.
This PR will not count towards your Hacktoberfest progression. Only PR's submitted during the event will count, and the event doesn't start for another 8d 13h. ([source](https://hacktoberfest.digitalocean.com/))

If you want, you could resubmit the PR in 8 days if you want it to count towards your progression? I can mark this issue as solved, and if the PR does not reappear within a couple days after start, I'll open the issue for others to try.

**Comment by ChaseBosman** [comment]
I'm not too concerned about it counting so it's up to you if you would like to pull it now. Just wanted to get my first pull request out of the way.

**Comment by svimanet** [comment]
Merged. Thank you for your contribution!

I leave the issue open if anyone wants to improve the feature.
